version: '3.8'

services:
  api:
    image: 'library-system-api:latest'
    container_name: api
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/library-system
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports: 
      - 8080:8080
          
  database:
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      - POSTGRES_DB=library-system
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
